# This is a basic workflow to help you get started with Actions
name: Update Lambda on AWS - DEV

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on: 
  workflow_dispatch:

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
 deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Identify Changed Lambda
        id: changed-lambda
        run: |
          # Get the name of the changed directory
          changed_dir=$(git diff --name-only HEAD^ | grep -oP 'lambda-\d+' | sort -u)
          echo "changed_lambda=${changed_dir}" >> $GITHUB_ENV
          echo "${changed_dir}"
     
      - name: Stop Workflow if No Changes
        if: env.changed_lambda == ''
        run: echo "No changes detected in any Lambda functions. Stopping the workflow." && exit 0

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.21.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Set your region
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubAssumeLambdaDevRole
          role-duration-seconds: 2400

      - name: Build
        run: |
          # Navigate to the changed Lambda directory
          go build -o bootstrap ./${{ env.changed_lambda }}/main.go 

      - name: Zip the name file
        run: zip main.zip bootstrap

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.changed_lambda }} \
            --zip-file fileb://main.zip
